mb_platform_home:
    path: /{page}
    defaults:
        _controller: MBPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

mb_platform_view:
    path: /advert/{id}
    defaults: {_controller: MBPlatformBundle:Advert:view}
    requirements:
        id: \d+

mb_platform_add:
    path: /add
    defaults: {_controller: MBPlatformBundle:Advert:add}

mb_platform_edit:
    path: /edit/{id}
    defaults: {_controller: MBPlatformBundle:Advert:edit}
    requirements:
        id: \d+

mb_platform_delete:
    path: /delete/{id}
    defaults: {_controller: MBPlatformBundle:Advert:delete}
    requirements:
        id: \d+
mb_platform_test:
    path: /testing
    defaults: {_controller: MBPlatformBundle:Advert:test}
