services:
#    mb_platform.example:
#        class: MB\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      
     mb_platform.antispam:
         class: MB\PlatformBundle\Antispam\MBAntispam
         arguments: [50]

     mb_platform.doctrine.notification:
         class: MB\PlatformBundle\DoctrineListener\ApplicationNotification
         arguments: [@mailer]
         tags: 
             - { name: doctrine.event_listener, event: postPersist }

     mb_platform.validator.antiflood:
         class: MB\PlatformBundle\Validator\AntifloodValidator
         arguments: [@request_stack, @doctrine.orm.entity_manager]
         tags:
             - {name: validator.constraint_validator, alias: mb_platform_antiflood}
